#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

function titleCaseLoose(s) {
  if (!s) return s;
  return s.slice(0, 1).toUpperCase() + s.slice(1);
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function isModifierCodePoint(cp) {
  const code = cp.codePointAt(0);
  return (
    (code >= 0x1f3fb && code <= 0x1f3ff) || // skin tone modifiers
    (code >= 0x1f9b0 && code <= 0x1f9b3) // hair modifiers
  );
}

function isModifierOnly(emoji) {
  if (!emoji) return false;
  let len = 0;
  for (const cp of emoji) {
    if (!isModifierCodePoint(cp)) return false;
    len++;
  }
  return len > 0;
}

const ROOT = path.resolve(process.cwd());
const dataPath = path.join(ROOT, 'node_modules', 'emojibase-data', 'en', 'data.json');
const messagesPath = path.join(ROOT, 'node_modules', 'emojibase-data', 'en', 'messages.json');
const outPath = path.join(ROOT, 'src', 'emoji-data.js');

if (!fs.existsSync(dataPath)) {
  console.error(`Missing ${dataPath}. Did you run npm install?`);
  process.exit(1);
}

const data = readJson(dataPath);
const messages = readJson(messagesPath);

const groups = (messages.groups || []).slice().sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
const groupByIndex = groups;

function groupKeyForEntry(e) {
  if (typeof e.group === 'number' && groupByIndex[e.group]) return groupByIndex[e.group].key;
  return 'component';
}

const byGroup = new Map();
for (const g of groups) byGroup.set(g.key, []);
if (!byGroup.has('component')) byGroup.set('component', []);

for (const e of data) {
  if (!e || typeof e.emoji !== 'string' || e.emoji.length === 0) continue;

  const groupKey = groupKeyForEntry(e);
  if (groupKey === 'component' && isModifierOnly(e.emoji)) continue;

  const entry = {
    emoji: e.emoji,
    label: e.label || '',
    group: groupKey,
    tags: Array.isArray(e.tags) ? e.tags : [],
    skins: Array.isArray(e.skins) ? e.skins.map((s) => s.emoji).filter(Boolean) : []
  };

  const arr = byGroup.get(groupKey) || [];
  arr.push(entry);
  byGroup.set(groupKey, arr);
}

const outGroups = [];
for (const g of groups) {
  outGroups.push({
    key: g.key,
    label: titleCaseLoose(g.message || g.key),
    emojis: byGroup.get(g.key) || []
  });
}

if (!outGroups.find((g) => g.key === 'component')) {
  outGroups.splice(2, 0, {
    key: 'component',
    label: 'Components',
    emojis: byGroup.get('component') || []
  });
}

const banner =
  '/* Generated by scripts/gen_emoji_data.mjs from emojibase-data. Do not edit by hand. */\n';
const js = banner + `export default ${JSON.stringify({ groups: outGroups })};\n`;

fs.writeFileSync(outPath, js, 'utf8');
console.log(`Wrote ${outPath} (${js.length} bytes)`);
